name: spacex_launches
description: "SpaceX API v3 Flutter application"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  http: ^1.1.0
  intl: ^0.18.0
  cached_network_image: ^3.2.3
  flutter_dotenv: ^5.0.2
  go_router: ^16.2.1
  smooth_page_indicator: ^1.0.0
  url_launcher: ^6.1.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/placeholder.jpg
